"""empty message

Revision ID: 202886105994
Revises: a9bbd8c6b0e8
Create Date: 2023-05-10 20:18:53.769374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202886105994'
down_revision = 'a9bbd8c6b0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
