"""empty message

Revision ID: 2aeebe6be845
Revises: 202886105994
Create Date: 2023-05-10 22:15:12.938486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aeebe6be845'
down_revision = '202886105994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
