"""empty message

Revision ID: 3cbdd9321ba8
Revises: 
Create Date: 2023-05-04 15:31:09.042921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbdd9321ba8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('numero_telefono', sa.String(length=10), nullable=False),
    sa.Column('contraseña', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('numero_telefono')
    )
    op.create_table('empleado',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('nombre_empleado', sa.String(length=70), nullable=True),
    sa.Column('tipo_empleado', sa.String(length=30), nullable=True),
    sa.Column('correo_empleado', sa.String(length=100), nullable=False),
    sa.Column('numero_telefono', sa.String(length=10), nullable=False),
    sa.Column('contraseña', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_empleado'),
    sa.UniqueConstraint('correo_empleado'),
    sa.UniqueConstraint('numero_telefono')
    )
    op.create_table('provedor',
    sa.Column('id_provedor', sa.Integer(), nullable=False),
    sa.Column('nombre_provedor', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('numero_telefono', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_provedor'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('numero_telefono')
    )
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_provedor', sa.Integer(), nullable=True),
    sa.Column('nombre_producto', sa.String(length=100), nullable=False),
    sa.Column('cantida', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('RutaImagen', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_provedor'], ['provedor.id_provedor'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    op.drop_table('provedor')
    op.drop_table('empleado')
    op.drop_table('cliente')
    # ### end Alembic commands ###
